name: yorum_pusulas
description: "tarafsiz bir yorum uygulamasi"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  csv: ^6.0.0 # CSV dosyalarını listeye çevirmek için en iyi paket
  flutter:
    sdk: flutter


  # --- FIREBASE ---
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0

  # --- DİĞER PAKETLER ---
  image_picker: ^1.1.0
  google_mlkit_image_labeling: ^0.13.0
  google_generative_ai: ^0.4.3
  translator: ^1.0.0
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#26A69A"
  adaptive_icon_foreground: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/ # Klasördeki tüm dosyaları (csv, png vb.) otomatik tanır